### ISSUE TITLE
Pausing 

### ISSUE THREAD

**Issue by KeyboardCamper** [KeyboardCamper/Arduboy-Snail-Maze#3]
Pausing displays the "Pause" but gameplay remains functional.

**Comment by KeyboardCamper** [comment]
Replaced 
`    if (arduboy.everyXFrames(60)){
      arduboy.setCursor(116, 0);
      counter = counter - 1;
      arduboy.print(counter);
      }`
With
`     if (arduboy.everyXFrames(60)){ 
      counter = counter - 1;}
     arduboy.setCursor(116, 0);
     arduboy.print(counter);`

**Comment by Pharap** [comment]
As of merged PR #5 ([Commit 26](https://github.com/KeyboardCamper/Arduboy-Snail-Maze/commit/4fe6d6c6b9a731da16994b3eae5c2ebfb7882532)), pause functionality is now working correctly.
